- name: add chrome apt key
  become: true
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: add chrome apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- name: install google-chrome
  become: true
  ansible.builtin.apt:
    name: google-chrome-stable
    update_cache: true

- name: add microsoft edge apt key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add microsoft edge apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
    filename: microsoft-edge
    state: present

- name: install microsoft edge
  become: true
  ansible.builtin.apt:
    name: microsoft-edge-stable
    update_cache: true

- name: install zen browser
  become: true
  community.general.flatpak:
    name: app.zen_browser.zen
    state: present
