- name: install docker build dependencies
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: add docker apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable

- name: install docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - pciutils # for lspci
    update_cache: true

- name: add {{ ansible_facts['user_id'] }} to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true

- name: Check if NVIDIA GPU is present
  ansible.builtin.shell: lspci | grep -i nvidia
  register: nvidia_gpu_check
  failed_when: false
  changed_when: false

- name: Install NVIDIA Container Toolkit if NVIDIA GPU is present
  import_tasks: nvidia_container_toolkit.yml
  when: nvidia_gpu_check.rc == 0
